### ISSUE TITLE
ncat reamains open after closing window

### ISSUE THREAD

**Issue by therealchisco** [therealchisco/cdmchat#1]
After exiting application and closing the tmux session and panes when attempting to reconnect 
we get the following error
`Ncat: bind to :::5214: Address already in use. QUITTING.
`
Perhaps it's because we are not exiting the ssh session properly

**Comment by erodrigufer** [comment]
[Ncat for sysadmins](https://www.redhat.com/sysadmin/ncat-security)

Again I will just quote the article... we are sooooo playing with fire here :)

> **_Remember to kill any ncat process that you don't want to continuously run once you're finished with it and remove the firewall exception that allows its access. Also, remember that with great power comes the ability to really screw things up._**

**Comment by erodrigufer** [comment]
Still gathering intel on this one. From a similar [Red Hat article](https://www.redhat.com/sysadmin/setting-tcp-listener):

> Disconnecting will also kill the TCP listening port on the remote (ncat) system, so don't attempt another connection until you reissue the ncat command. If you want to keep the listening port open rather than letting it die each time you disconnect, issue the -k (keep open) option. This option keeps the listening port alive. Some sysadmins don't use this option because they might leave a listening port open potentially causing security problems or port conflicts with other services.

**Comment by erodrigufer** [comment]
Use ```killall ncat``` to close all ports open previously by an ```ncat``` command.

**Comment by erodrigufer** [comment]
If using the C implementation of a multi-client TCP server, the ports can be closed by also closing a socket.
